---
- name: Create user for future deployments
  hosts: all
  become: yes
  tasks:
    - name: Create User
      ansible.builtin.user:
        name: ender
    - name: Copy public SSH Key
      ansible.posix.authorized_key:
        user: ender
        state: present
        key: "{{ lookup('file', '/home/srvadmin/.ssh/id_rsa_ender.pub') }}"
    - name: Add user to sudoers without password
      community.general.sudoers:
        name: 99-ansible
        user: ender
        nopassword: true
        commands: ALL

