---
- name: Desinstall Postgresql Servers
  hosts: dbserver
  become: yes
  tasks:
    - name: Apt remove PostgreSQL
      apt:
        name: postgresql-{{ item }}
        state: absent
      ignore_errors: true
      loop:
        - 14
        - 15
        - 16
      