---
- name: Install Database
  hosts: dbserver
  become: yes
  tags: DB
  roles:
    - common
    - db 

- name: Install Application
  hosts: appserver
  become: yes
  tags: APP
  roles:
    - common
    - app