---
- name: Install App Server
  hosts: nodeserver
  become: yes
  vars:
    app_dir: /usr/src/app
    owner: ender
  tasks:
    - name: Debug var app_dir
      ansible.builtin.debug:
        var: app_dir
    - name: Debug variables
      ansible.builtin.debug:
        msg:
          - dbname = {{ dbname }}
          - artifacts directory = {{ dir_artifacts }}
          - artifact node app = {{ app_artifact }}
    - name: Create directory
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ owner }}"
        group: "{{ owner }}"
        mode: 0750
    - name: Copy artifact
      ansible.builtin.copy:
        src: "{{ dir_artifacts }}/{{ app_artifact }}" 
        dest: "{{ app_dir }}"
        owner: "{{ owner }}"
        group: "{{ owner }}"
        mode: 0640
    - name: Install nodejs
      ansible.builtin.apt:
        name: nodejs

- name: Install DB Server
  hosts: dbserver
  become: yes
  tasks:
    - name: Install package gpg
      ansible.builtin.apt:
        name: gpg

    - name: Add GPG Key of Postgresql Repository
      ansible.builtin.apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    
    - name: Add Postgresql Repository
      ansible.builtin.apt_repository:
        repo: deb https://apt.postgresql.org/pub/repos/apt bookworm-pgdg main
        filename: postgresql

    - name: Install Postgresql
      ansible.builtin.apt:
        name: postgresql-{{ postgresql_version }}
        update_cache: yes